### ISSUE TITLE
资产管理界面 这个还木有做吧？

### ISSUE THREAD

**Issue by vTNT** [alaxli/ansible_ui#2]
demo上还没看到

**Comment by bagmdgiveme** [comment]
我的也是一直pending状态
谁能解决下。

**Comment by alaxli** [comment]
看看后台celery进程的状态是否正常来自我的华为手机-------- 原始邮件 --------主题：Re: [ansible_ui] 资产管理界面 这个还木有做吧？ (#2)发件人：bagmdgiveme 收件人：alaxli/ansible_ui 抄送：alex_li 我的也是一直pending状态
谁能解决下。

**Comment by bagmdgiveme** [comment]
![image](https://cloud.githubusercontent.com/assets/11439184/6633732/281f8da2-c988-11e4-8e83-68921a609896.png)

**Comment by alaxli** [comment]
celery进程没起来，应有 manage.py celery worker -B -l info 进程来自我的华为手机-------- 原始邮件 --------主题：Re: [ansible_ui] 资产管理界面 这个还木有做吧？ (#2)发件人：bagmdgiveme 收件人：alaxli/ansible_ui 抄送：alex_li

**Comment by bagmdgiveme** [comment]
ansible_ui资产管理优点不是很明显吧？
是环境变量问题吗？？
ansible的环境变量怎么设置呢。
![image](https://cloud.githubusercontent.com/assets/11439184/6680792/f6703a1a-cc96-11e4-94eb-ecb1ae947f60.png)

**Comment by bagmdgiveme** [comment]
有例子没，搞个例子，看下，研究研究

**Comment by bagmdgiveme** [comment]
之前的问题就是环境变量的问题，已解决，
现在有新问题。

**Comment by bagmdgiveme** [comment]
状态：failed
stdout

ERROR: tasks is not a legal parameter in an Ansible task or handler

**Comment by bagmdgiveme** [comment]
[root@cenos playbooks]# cat ping2.yml 
- hosts: all
  remote_user: root
  #gather_facts: False
  tasks:
    - name: echo hi
      shell: echo "hi"
  handlers:
#    - include: ./ping2.yml 

这个yml用ansible-playbook ping2.yml   执行是没有问题的。

**Comment by bagmdgiveme** [comment]
[root@cenos playbooks]# ansible-playbook ping2.yml 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
fatal: [192.168.106.42] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
fatal: [192.168.106.43] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
fatal: [192.168.106.44] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
ok: [192.168.194.65]
ok: [10.6.1.32]

TASK: [echo hi] *************************************************************** 
changed: [192.168.194.65]
changed: [10.6.1.32]

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/ping2.retry

10.6.1.32                  : ok=2    changed=1    unreachable=0    failed=0   
192.168.106.42             : ok=0    changed=0    unreachable=1    failed=0   
192.168.106.43             : ok=0    changed=0    unreachable=1    failed=0   
192.168.106.44             : ok=0    changed=0    unreachable=1    failed=0   
192.168.194.65             : ok=2    changed=1    unreachable=0    failed=0

**Comment by alaxli** [comment]
可以查看下失败的机器上相应的账号中，是否有ansible_ui中配置的用户公钥， ansible_ui 会使用配置的公钥，直接执行使用的是机器上的密钥，这点有可能不同

**Comment by jiafeicat** [comment]
打算将python manage.py runserver改为nginx+uwsgi, 但是没改成功, 折腾了一下午. 再接在励了.   你们有整合到nginx吗?

**Comment by alaxli** [comment]
已增加nginx+uwsgi的配置，包含 ansible_uwsgi.ini , ansible.wsgi, nginx-conf/nginx_ansible.conf
